### ISSUE TITLE
Update for Pandoc 2.x

### ISSUE THREAD

**Issue by byorgey** [wei2912/blog-src#9]
Hi @wei2912 , I saw your question on `#hakyll` after you had already left, and this seemed like the easiest way to respond.  Your errors are caused by upgrading from Pandoc 1.x to Pandoc 2.x.  On the following line you want to change `S.insert` to `enableExtension`:

https://github.com/wei2912/blog_src/blob/03b5190a9e1c729820e51017641080cf622a3d55/src/site.hs#L58

I think that will be sufficient but I am not 100% sure.  Feel free to ping me if not.  I recently upgraded my own site similarly so we should be able to figure it out.

**Comment by wei2912** [comment]
This has been resolved, thanks!
